#!/bin/bash
set -x

cat << EOF > config
sy=2016
sm=06
sd=18
ey=2017
em=06
ed=30
monthly=1
publish=0
suffix=aggregate
prefix=aggregate
csvalljobs=/app/nsccadmin/log/printjob/alljobs.csv
EOF

. ./config
make config.py

pbsreportrawalpha=pbs-report.raw.alpha.csv
pbsreportrawproduction=pbs-report.raw.production.csv
pbsreportrawaggregate=pbs-report.raw.$suffix.csv
pbsreportcleanedalpha=pbs-report.cleaned.alpha.csv
pbsreportcleanedproduction=pbs-report.cleaned.production.csv
pbsreportcleanedaggregate=pbs-report.cleaned.$suffix.csv

make $pbsreportrawaggregate
if [ $pbsreportrawaggregate -nt $pbsreportcleanedproduction ] ; then echo rm -f $pbsreportcleanedproduction ; fi

if [ ! -f $pbsreportcleanedproduction ] ; then
 rm -f $pbsreportcleanedaggregate && \
  make $pbsreportcleanedaggregate && \
  mv $pbsreportcleanedaggregate $pbsreportcleanedproduction || \
  rm -f $pbsreportcleanedaggregate $pbsreportcleanedproduction
fi

if [ ! -f $pbsreportcleanedalpha ] ; then
 # Alpha Phase
 d=20160328-20160617
 g=../$d/pbs-report.cleaned.$d.csv
 head -n 2 $g > $pbsreportcleanedalpha && \
  tail -n +3 $g | sed -e 's,^,A,' >> $pbsreportcleanedalpha || \
  rm -f $pbsreportcleanedalpha
fi

cp $pbsreportcleanedalpha $pbsreportcleanedaggregate && \
 tail -n +3 $pbsreportcleanedproduction >> $pbsreportcleanedaggregate || \
 rm -f $pbsreportcleanedaggregate
