#!/bin/bash
cd `dirname "$0"` || exit $?

. ./config
if [ x"$statsuser" == x ] ; then statsuser="${LOGNAME}" ; fi
if [ x"$statsgroup" == x ] ; then statsgroup="root" ; fi

# Turn off execute bit on log files (fixes files copied in from Windows)
 if [ -d "$logdir" ] ; then
 find "$logdir" -type f -a -perm /0111 -exec chmod a-x {} \;
fi

if [ x"$1" == x--full ] ; then
 for d in "$PWD" "$logdir" ; do
  if [ -d "$d" ] ; then
   # Set appropriate file permissions on data
   chown -R ${statsuser}.${statsgroup} "$d"
   chmod -R u+rwX,g-w,g+rX,o-rwx "$d"
   setfacl -R -bk "$d"
  fi
 done
else
 chown ${statsuser}.${statsgroup} *
 chown -R ${statsuser}.${statsgroup} dgx load2apps R-stats-trending system-utilisation
 chown -R ${statsuser}.${statsgroup} "$logdir"
fi

setfacl -m u:${am_u}:rw "$logdir"/am-*
setfacl -m u:${am_u}:rwx "$logdir" "$logdir/weekly" "$logdir/aggregate"
