#!/bin/bash

. ./config

rawfile="pbs-report.raw.$suffix.csv"
csvfile="pbs-report.intermediate.$suffix.csv"
csvfile2="pbs-report.final.$suffix.csv"

if [ ! -f "$rawfile" ] ; then
 echo running pbs-report
 pbs-report --verbose --csv "|" --begin $sy$sm$sd --end $ey$em$ed --time full > "$rawfile" || exit $?
fi

if [ ! -f "$csvfile" ] ; then
echo cleaning output
((n=0))
while read line ; do
if [ x"$line" = x ] ; then ((n=n+1)) ; continue ; fi
if [ $n -eq 2 ] ; then
 echo "$line" | sed -e 's,Suspend$,Suspend|,' | \
   awk -F\| '{if ( NF == 16 ) {OFS="|" ; a=$4"_"$5 ; print $1,$2,$3,a,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16;} else \
             {if ( NF == 17 ) {OFS="|" ; a=$4"_"$5"_"$6 ; print $1,$2,$3,a,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17;} else {print $0;};};}'
fi
done < "$rawfile" > "$csvfile"
check=`awk -F\| '{print NF}' "$csvfile" | uniq`
if [ x"$check" != x15 ] ;then echo ERROR: cleaning data shows malformed data: $check ; exit 1 ; fi
fi

if [ ! -f "$csvfile2" ] ; then
rm -f "$csvfile2"
while read -r line ; do
 hosts=`echo "$line" | awk -F\| '{print $(NF-8)}'`
 if [ x"$hosts" != xExecution -a x"$hosts" != x"Host(s)" ] ; then
  hosts2bc=`echo $hosts | sed -e "s/-ib0//g" -e "s,wlm0[0-9]/[0-9]*,1,g" -e "s,vis[0-9][0-9]/[0-9]*\*,,g" -e "s,vis[0-9][0-9]/[0-9]*,1,g" -e "s,[a-z]*[0-9][0-9][0-9][0-9]/[0-9]*\*,,g" -e "s,[a-z]*[0-9][0-9][0-9][0-9]/[0-9]*,1,g"`
  cores=`echo $hosts2bc | bc`
  if [ x"$cores" = x ] ; then echo $jobid $hosts ; break ; fi
  hosts_s="${hosts//\*/\*}"
  line_mod=`echo "$line" | sed -e "s%${hosts_s}%${cores}%"`
   if [ x"$line_mod" = "x$line" ] ; then
     echo line=$line
     echo hosts="$hosts"
     echo hosts2bc="$hosts2bc"
     echo cores="$cores"
     echo line_mod="$line_mod"
     break
   fi
  echo "$line_mod" >> "$csvfile2"
 else
  echo "$line" >> "$csvfile2"
 fi
done < "$csvfile"
fi
