#!/bin/bash

cd `dirname $0`
pwd
. ./config

export PATH="/app/pbs/bin:$PATH:/opt/pbs/bin:/opt/pbs/sbin"
. /etc/profile.d/modules.sh
. /app/modules/modules.sh
module load R
which Rscript

echo making boxplots
xvfb-run Rscript PBS-wait-boxplots.R
