#!/bin/bash
. ./config

dotm=31
# won't work in leap year
if [ $em == "02" ] ; then
 ((ly=ey%4))
 if [ $ly -eq 0 ] ; then
  dotm=29
 else
  dotm=28
 fi
elif [ $em == "04" ] ; then
  dotm=30
elif [ $em == "06" ] ; then
  dotm=30
elif [ $em == "09" ] ; then
  dotm=30
fi

ed=${ed#0}
em=${em#0}
((ed=ed+1))
if [ $ed -gt $dotm ] ; then
 ((ed=1))
 ((em=em+1))
fi
if [ $em -eq 13 ] ; then
 ((em=1))
 ((ey=ey+1))
fi

if [ $ed -lt 10 ] ; then ed=0$ed ; fi
if [ $em -lt 10 ] ; then em=0$em ; fi

stem="/app/nsccadmin/log/ams/ams-projects"
file=`ls -1t "${stem}.${ey}${em}${ed}"*.csv 2>/dev/null | head -n 1`
if [ x"$file" == x ] ; then
  file=`ls -1t "${stem}".*.csv | head -n 1`
fi
if [ ! -f "$file" ] ; then echo ERROR: no AMS file ; exit 1 ; fi

csv="ams-personal.$suffix.csv"
head -1 "$file" | awk -F, '{printf "%s,%s,%s,%s,%s,fraction_used\n",$1,$7,$8,$9,$5}' > "$csv"
tail -n +2 "$file" | grep    ^personal- | sed -e "s/^personal-//" \
  | awk -F, '{printf "%s,%.1f,%.1f,%.1f,%.1f,%.3f\n",$1,$7,$8,$9,$5,$7/$5}' \
  | sort -t, -rnk 2,2 >> "$csv"

csv="ams-projects.$suffix.csv"
head -1 "$file" | awk -F, '{printf "%s,%s,%s,%s,%s,fraction_used,%s\n",$1,$7,$8,$9,$5,$2}' > "$csv"
tail -n +2 "$file" | grep -v ^personal- \
  | awk -F, '{printf "%s,%.1f,%.1f,%.1f,%.1f,%.3f,%s\n",$1,$7,$8,$9,$5,$7/$5,$2}' \
  | sort -t, -rnk 2,2 >> "$csv"
