#!/bin/bash
## set -x
set -eu
users=`getent passwd | awk -F: '{printf "%s ",$1}'`

. ./config

logdir=/app/nsccadmin/log/storage-statistics
datestring="${ey}${em}${ed}-12:00"

csv="storage.$suffix.csv"

echo '"Username","home_gb","home_files","home1_gb","home1_files","secure_gb","secure_files","scratch_gb","scratch_files","seq_gb","seq_files"' > $csv

users=`getent passwd | awk -F: '{printf "%s ",$1}'`
for user in $users ; do

fs=home
home_gb=`grep "^$user " $logdir/$fs.user.quota.$datestring | sed -e 's/ days/_days/' | awk 'BEGIN {sum=0;} {sum=sum+$3;} END {printf "%d",sum;}'`
home_files=`grep "^$user " $logdir/$fs.user.quota.$datestring | sed -e 's/ days/_days/' | awk 'BEGIN {sum=0;} {sum=sum+$9;} END {printf "%d",sum;}'`
fs=home1
home1_gb=`grep "^$user " $logdir/$fs.user.quota.$datestring | sed -e 's/ days/_days/' | awk 'BEGIN {sum=0;} {sum=sum+$4;} END {printf "%d",sum;}'`
home1_files=`grep "^$user " $logdir/$fs.user.quota.$datestring | sed -e 's/ days/_days/' | awk 'BEGIN {sum=0;} {sum=sum+$10;} END {printf "%d",sum;}'`
fs=secure
secure_gb=`grep "^$user " $logdir/$fs.user.quota.$datestring | sed -e 's/ days/_days/' | awk 'BEGIN {sum=0;} {sum=sum+$3;} END {printf "%d",sum;}'`
secure_files=`grep "^$user " $logdir/$fs.user.quota.$datestring | sed -e 's/ days/_days/' | awk 'BEGIN {sum=0;} {sum=sum+$9;} END {printf "%d",sum;}'`

fs=scratch
scratch_gb=`grep "^$user " $logdir/$fs.user.quota.$datestring | sed -e 's/ days/_days/' | awk 'BEGIN {sum=0;} {sum=sum+$4;} END {printf "%d",sum/1e6;}'`
scratch_files=`grep "^$user " $logdir/$fs.user.quota.$datestring | sed -e 's/ days/_days/' | awk 'BEGIN {sum=0;} {sum=sum+$8;} END {printf "%d",sum;}'`
fs=seq
seq_gb=`grep "^$user " $logdir/$fs.user.quota.$datestring | sed -e 's/ days/_days/' | awk 'BEGIN {sum=0;} {sum=sum+$4;} END {printf "%d",sum/1e6;}'`
seq_files=`grep "^$user " $logdir/$fs.user.quota.$datestring | sed -e 's/ days/_days/' | awk 'BEGIN {sum=0;} {sum=sum+$8;} END {printf "%d",sum;}'`

## grep "^$user " $logdir/*.user.quota.$datestring || true
## echo ${user},${home_gb},${home_files},${home1_gb},${home1_files},${secure_gb},${secure_files},${scratch_gb},${scratch_files},${seq_gb},${seq_files} | tee -a $csv
##echo
echo ${user},${home_gb},${home_files},${home1_gb},${home1_files},${secure_gb},${secure_files},${scratch_gb},${scratch_files},${seq_gb},${seq_files} >> $csv
done
