#!/bin/bash
. ./config

type git > /dev/null 2>&1 || exit 0

find . -name .git -type d | sed -e 's,/.git,,' | while read d ; do (cd $d && git pull) ; done

if [ ! -d dgx ] ; then git clone $repos/usage-dgx.git dgx ; fi
if [ ! -d system-utilisation ] ; then git clone $repos/system-utilisation.git ; fi
if [ ! -d load2apps ] ; then git clone $repos/load2apps.git ; fi
if [ ! -d am ] ; then git clone $repos/usage-pbs-am.git am ; fi
