#!/bin/bash
##set -x
set -eu
#users=`getent passwd | awk -F: '{printf "%s ",$1}'`
users=`ldapsearch -xxx | grep '^dn: uid' | sed -e "s/^dn: uid=//" -e "s/,.*//" | sort | uniq`
users="root $users"

. ./config

logdir=/app/nsccadmin/log/storage-statistics
datestring="${ey}${em}${ed}-12:00"

csv="storage.$suffix.csv"

if [ ! -f "$csv" ] ; then
echo '"Username","home_gb","home_files","home1_gb","home1_files","secure_gb","secure_files","scratch_gb","scratch_files","seq_gb","seq_files"' > $csv

for user in $users ; do

fs=home
f="$logdir/$fs.user.quota.$datestring"
if [ ! -f "$f" ] ; then f=`ls -1 "$logdir/$fs.user.quota".* | tail -1` ; fi
home_gb=`grep "^$user " $f | sed -e 's/ days/_days/' | awk 'BEGIN {sum=0;} {sum=sum+$3;} END {printf "%d",sum;}'`
home_files=`grep "^$user " $f | sed -e 's/ days/_days/' | awk 'BEGIN {sum=0;} {sum=sum+$9;} END {printf "%d",sum;}'`
fs=home1
f="$logdir/$fs.user.quota.$datestring"
if [ ! -f "$f" ] ; then f=`ls -1 "$logdir/$fs.user.quota".* | tail -1` ; fi
home1_gb=`grep "^$user " $f | sed -e 's/ days/_days/' | awk 'BEGIN {sum=0;} {sum=sum+$4;} END {printf "%d",sum;}'`
home1_files=`grep "^$user " $f | sed -e 's/ days/_days/' | awk 'BEGIN {sum=0;} {sum=sum+$10;} END {printf "%d",sum;}'`
fs=secure
f="$logdir/$fs.user.quota.$datestring"
if [ ! -f "$f" ] ; then f=`ls -1 "$logdir/$fs.user.quota".* | tail -1` ; fi
secure_gb=`grep "^$user " $f | sed -e 's/ days/_days/' | awk 'BEGIN {sum=0;} {sum=sum+$3;} END {printf "%d",sum;}'`
secure_files=`grep "^$user " $f | sed -e 's/ days/_days/' | awk 'BEGIN {sum=0;} {sum=sum+$9;} END {printf "%d",sum;}'`

fs=scratch
f="$logdir/$fs.user.quota.$datestring"
if [ ! -f "$f" ] ; then f=`ls -1 "$logdir/$fs.user.quota".* | tail -1` ; fi
#scratch_gb=`grep "^$user " $f | sed -e 's/ days/_days/' | awk 'BEGIN {sum=0;} {sum=sum+$4;} END {printf "%d",sum/1e6;}'`
#scratch_files=`grep "^$user " $f | sed -e 's/ days/_days/' | awk 'BEGIN {sum=0;} {sum=sum+$8;} END {printf "%d",sum;}'`
scratch_gb=`grep "^$user " $f | sed -e 's/ days/_days/' | sed -e 's/\[//' -e 's/\]//' | awk 'BEGIN {sum=0;} {sum=sum+$4;} END {printf "%d",sum/1e6;}'`
scratch_files=`grep "^$user " $f | sed -e 's/ days/_days/' | sed -e 's/\[//' -e 's/\]//'  | awk 'BEGIN {sum=0;} {sum=sum+$8;} END {printf "%d",sum;}'`
fs=seq
f="$logdir/$fs.user.quota.$datestring"
if [ ! -f "$f" ] ; then f=`ls -1 "$logdir/$fs.user.quota".* | tail -1` ; fi
seq_gb=`grep "^$user " $f | sed -e 's/ days/_days/' | awk 'BEGIN {sum=0;} {sum=sum+$4;} END {printf "%d",sum/1e6;}'`
seq_files=`grep "^$user " $f | sed -e 's/ days/_days/' | awk 'BEGIN {sum=0;} {sum=sum+$8;} END {printf "%d",sum;}'`

## grep "^$user " $logdir/*.user.quota.$datestring || true
## echo ${user},${home_gb},${home_files},${home1_gb},${home1_files},${secure_gb},${secure_files},${scratch_gb},${scratch_files},${seq_gb},${seq_files} | tee -a $csv
##echo
echo ${user},${home_gb},${home_files},${home1_gb},${home1_files},${secure_gb},${secure_files},${scratch_gb},${scratch_files},${seq_gb},${seq_files} >> $csv
done
fi

# project filesets
csvp="storage-byproject."$suffix".csv"
if [ ! -f $csvp ] ; then
f="$logdir/home.fileset.quota.$datestring"
f1="$logdir/home1.fileset.quota.$datestring"
if [ ! -f "$f" ] ; then f=`ls -1 "$logdir/home.fileset.quota".* | tail -1` ; fi
if [ ! -f "$f1" ] ; then f1=`ls -1 "$logdir/home1.fileset.quota".* | tail -1` ; fi
echo 'Project,home_gb' > "$csvp"
getent group | grep '^[1-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' | sed -e 's,:.*,,' | while read p  ; do s=`grep "^$p " "$f" | awk '{print $3}'` ; s1=`grep "^$p " "$f1" | awk '{print $4}'` ; if [ x"$s1" != x ] ; then ((s=s+s1)) ; fi ; echo $p,$s ; done >> "$csvp"
sed -i \
 -e 's/^11/NUS-11/' \
 -e 's/^12/NTU-12/' \
 -e 's/^13/A*STAR-13/' \
 -e 's/^14/Industry-14/' \
 -e 's/^15/SUTD-15/' \
 -e 's/^16/NIS-16/' \
 -e 's/^2/Industry-2/' \
 -e 's/^41/DGX-41/' \
 -e 's/^90/NSCC-90/' \
 "$csvp"
fi

# all filesets
csvf="storage-byfileset.$suffix.csv"
if [ ! -f $csvf ] ; then
echo 'Fileset,GB,quota,Filesystem' > "$csvf"
for fs in home home1 ; do
 f="$logdir/$fs.fileset.quota.$datestring"
 if [ ! -f "$f" ] ; then f=`ls -1 "$logdir/$fs.fileset.quota."* | tail -1` ; fi
 if [ x"$fs" == xhome ] ; then
  tail -n +3 "$f" | awk '{printf "'${fs}':%s,%s,%s,'${fs}'\n",$1,$3,$4}'
 else
  tail -n +3 "$f" | awk '{printf "'${fs}':%s,%s,%s,'${fs}'\n",$1,$4,$5}'
 fi
done | sort -t, -rnk 2,2 >> "$csvf"
fi


csvf="storage-fileset-category.$suffix.csv"
if [ ! -f $csvf ] ; then
echo Fileset,type > $csvf
fs="home"
for user in $users ; do
 if [ x"$user" == xroot ] ; then
  echo ${fs}:${user},HOME_NOT_FILESET >> $csvf
 else
  echo ${fs}:${user},HOME_HOMEDIRS >> $csvf
 fi
done
projects=`getent group | grep '^[1-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]:' | awk -F: '{printf "%s ",$1}'`
for proj in $projects ; do
 echo home:${proj},HOME_PROJECTS >> $csvf
 echo home1:${proj},DATA_PROJECTS >> $csvf
done
echo home:csibio,HOME_PROJECTS_CSIBIO >> $csvf
fi
