#!/bin/bash

. ./config

for f in config.R ; do
 if [ ! -f $f ] ; then
  eval ./make-$f
 fi
done

# R script to merge output from pbs-report with job application statistics
scripts="Storage.R Storage-Fileset.R PBS-Application-Stats-Clean.R PBS-Application-Stats-Combined.R ProjectInfo.R PBS-Application-Stats-Project.R PBS-Application-Stats-Active.R"

# base directory
base=/app/nsccadmin/log

# reduce size of ancillary files
./filter-alljobs

type Rscript > /dev/null 2>&1 || module load R
# Run the script to generate csv files with statistics
for script in $scripts ; do
 echo running $script
 Rscript "$script"
done

if [  ${publish:-0} -eq 1 ] ; then ./make-publish ; fi
