#!/bin/bash
ulimit -m 67108864
ulimit -v 67108864

. ./config

q=production

rawfile="$q.pbs-report.raw.$suffix.csv"
if [ ! -f "$rawfile" ] ; then
tmpfile="$rawfile".tmp

if [ x$HOSTNAME$USER != xwlm01root ] ; then
 echo ssh to root@wlm01 to run pbs-report
 ssh root@wlm01 "ulimit -m 67108864 ; ulimit -v 67108864 ; pbs-report --verbose --csv \| --begin $sy$sm$sd --end $ey$em$ed --time partial -q $q" > "$tmpfile" || rm -f "$tmpfile"
else
 echo running pbs-report
 pbs-report --verbose --csv "|" --begin $sy$sm$sd --end $ey$em$ed --time partial -q $q > "$tmpfile" || rm -f "$tmpfile"
fi

mv "$tmpfile" "$rawfile"
fi

./pbsreport-clean-$q.py
./pbsreport-count-cores-$q.py
type Rscript > /dev/null 2>&1 || module load R
Rscript Unused-$q.R
