#!/bin/bash
ulimit -m 67108864
ulimit -v 67108864

. ./config

q=production

rawfile="$q.pbs-report.raw.$suffix.csv"
if [ ! -f "$rawfile" ] ; then
tmpfile="$rawfile".tmp

if [ x$HOSTNAME$USER != xwlm01root ] ; then
 echo ssh to root@wlm01 to run pbs-report
 ssh root@wlm01 "ulimit -m 67108864 ; ulimit -v 67108864 ; pbs-report --verbose --csv \| --begin $sy$sm$sd --end $ey$em$ed --time partial -q $q" > "$tmpfile" || rm -f "$tmpfile"
else
 echo running pbs-report
 pbs-report --verbose --csv "|" --begin $sy$sm$sd --end $ey$em$ed --time partial -q $q > "$tmpfile" || rm -f "$tmpfile"
fi

mv "$tmpfile" "$rawfile"
fi

if grep 'No results matched your query' production.pbs-report.raw.$suffix.csv ; then
cat << EOF > production.pbs-report.cleaned.$suffix.csv
||||Date/Time||Execution||Core|Virtual|Used|Used|Queue|Suspend
Job ID|Username|Queue|Job Name|Created|Package|Host(s)|Nodes|Memory|Memory|CPU Time|Wall Time|Wait Time|Time|Exit 
1|joebloggs|production|jobname|2017/10/16 12:08|None|std0101/0*23|1|0kb|0kb|0|14|2686181|0|-2
EOF
else
./pbsreport-clean-$q.py
fi
./pbsreport-count-cores-$q.py
type Rscript > /dev/null 2>&1 || module load R
Rscript Unused-$q.R
