#!/bin/bash

. ./config

for f in config.R ; do
 if [ ! -f $f ] ; then
  eval ./make-$f
 fi
done

# High level institutes
orgs="ASTAR NUS NTU CREATE"
# Individual organizations
orgs="$orgs GIS IHPC"
#orgs="$orgs BEARS-BERKELEY CARES E2S2 ETHZ NRD SINBERBEST SINBERISE SMART TUM-CREATE"

# R script to merge output from pbs-report with job application statistics
scripts="PBS-Application-Stats-Clean.R PBS-Application-Stats-Combined.R"

# base directory
base=/app/nsccadmin/log

type Rscript > /dev/null 2>&1 || module load R
# Run the script to generate csv files with statistics
for script in $scripts ; do
 echo running $script
 Rscript "$script"
done

# Make zip file for each organisation
makezip=${makezip:-0}
if [ $makezip -eq 1 ] ; then
for org in $orgs ; do
  rm -rf ${prefix}-${org} && \
  mkdir ${prefix}-${org} && \
  cp -p *.${org}.${suffix}.csv ${prefix}-${org} && \
  rm -f ${prefix}-${org}.zip && \
  zip -r ${prefix}-${org}.zip ${prefix}-${org} && \
  rm -rf ${prefix}-${org}
done
fi

if [  ${publish:-0} -eq 1 ] ; then
 # Copy NUS data to Junhong home directory
 cp -ip *.NUS.* ~ccewjh/Monthly_Usage/ < /dev/null
 chown ccewjh.nus ~ccewjh/Monthly_Usage/*
 # Copy NTU data to Melvin home directory
 cp -ip *.NTU* ~melvin/Monthly_Usage/ < /dev/null
 chown melvin.ntu ~melvin/Monthly_Usage/*
fi

# Copy data to log directory
if [  ${publish:-0} -eq 1 ] ; then
logdir=$base/usage-statistics
outputfiles=`echo {alldata,top100,total,org,application,user_}*.$suffix.csv`
if [ $monthly -eq 1 ] ; then
 cp -pv $outputfiles $logdir/
 mkdir -p $logdir/by-org
 for org in $orgs ; do
  mv -v $logdir/*.$org.$suffix.csv $logdir/by-org/
  mkdir -p by-org && mv *.$org.$suffix.csv by-org/
 done
else
 mkdir -p $logdir/weekly
 cp -pv $outputfiles $logdir/weekly/
fi

# Set appropriate file permissions on data
for d in "$PWD" "$logdir" ; do
 setfacl -R -bk "$d" ;  chmod -R u+rwX,g+rX,o-rwx "$d" ; chown -R ${LOGNAME}.nscc-proj "$d"
done
fi
