#!/bin/bash

. ./config

copyout(){
 stakeholder="$1"
 rep_u="$2"
 rep_g="$3"
 yes | eval /bin/cp -f -p *.$stakeholder.$suffix.csv dgx/*.$stakeholder.$suffix.csv ~${rep_u}/Monthly_Usage/
 eval chown ${rep_u}.${rep_g} ~${rep_u}/Monthly_Usage/*.$stakeholder.$suffix.csv
}

# Copy NUS data to Junhong home directory
copyout NUS ccewjh nus
# Copy NTU data to Melvin home directory
copyout NTU melvin ntu
