#!/bin/bash

. ./config

usernames_csv="usernames.$suffix.csv"
usernames_raw_csv="usernames-raw.$suffix.csv"
rm -f "$usernames_csv" "$usernames_raw_csv"

# Get cached version if available
if [ -f "$csvusernames" ] ; then cp -p "$csvusernames" "$usernames_csv" && exit ; fi

# Gather raw username information
echo Username,Name,Organization,Organization.HighLevel,cn,sn,givenName,displayName > "$usernames_raw_csv"
echo Username,Name,Organization,Organization.HighLevel > "$usernames_csv"
#missing usernames
echo nus.junhong,nus.junhong,NUS,NUS,,,, >> "$usernames_raw_csv"
echo nus.junhong,nus.junhong,NUS,NUS >> "$usernames_csv"
echo a0098651,Zhou Jun Zhou,NUS,NUS,,,, >> "$usernames_raw_csv"
echo a0098651,Zhou Jun Zhou,NUS,NUS >> "$usernames_csv"
# users to simulate system activity
for u in  marzinek1 lijg1 ngmf1 markovav1 yeojj1 minh00061 chinmayi1 ngtz00131 chan07261 amirzoev1 ceeao2 dbsmjk1 e00958601 gmsliji1 smrmom1 hsianghe1 smrlxu1 s1002620 lunna_li1 s1002631 tb1 s1002535 helenzh11 ; do
 ou="NSCC"
 ouh="Other"
 name="NSCC User"
 mail="help@nscc.sg"
 echo ${u},${name},${ou},${ouh} >>  "$usernames_csv"
 echo ${u},${name},${ou},${ouh},,,, >> "$usernames_raw_csv"
done

getent passwd | awk -F: '{print $1}' | while read username ; do

_x=`ldapsearch -x -LLL "(uid=$username)"`
if [ x"$_x" != x ] ; then
 cn=`ldapsearch -x -LLL "(uid=$username)" | grep ^cn: | sed -e "s,^cn. ,," -e 's/,/ /g' -e 's/  */ /g' -e 's/#//g' -e 's/([^)]*)//' -e 's/ *$//' -e 's/^ *//' | tr '[A-Z]' '[a-z]' | perl -ane ' foreach $wrd ( @F ) { print ucfirst($wrd)." "; } print "\n" ; ' | sed -e 's/ *$//' -e 's/^ *//'`
 sn=`ldapsearch -x -LLL "(uid=$username)" | grep ^sn: | sed -e "s,^sn. ,," -e 's/,/ /g' -e 's/  */ /g' -e 's/#//g' -e 's/([^)]*)//' -e's/ *$//' -e 's/^ *//' | tr '[A-Z]' '[a-z]' | perl -ane ' foreach $wrd ( @F ) { print ucfirst($wrd)." "; } print "\n" ; ' | sed -e 's/ *$//' -e 's/^ *//'`
 gn=`ldapsearch -x -LLL "(uid=$username)" | grep ^givenName: | sed -e "s,^givenName. ,," -e 's/,/ /g' -e 's/  */ /g' -e 's/#//g' -e 's/([^)]*)//' -e's/ *$//' -e 's/^ *//' | tr '[A-Z]' '[a-z]' | perl -ane ' foreach $wrd ( @F ) { print ucfirst($wrd)." "; } print "\n" ; ' | sed -e 's/ *$//' -e 's/^ *//'`
 dn=`ldapsearch -x -LLL "(uid=$username)" | grep ^displayName: | sed -e "s,^displayName. ,," -e 's/,/ /g' -e 's/  */ /g' -e 's/#//g' -e 's/([^)]*)//' -e's/ *$//' -e 's/^ *//' | tr '[A-Z]' '[a-z]' | perl -ane ' foreach $wrd ( @F ) { print ucfirst($wrd)." "; } print "\n" ; ' | sed -e 's/ *$//' -e 's/^ *//'`
 ou=`ldapsearch -x -LLL "(uid=$username)" | grep ^dn: | sed -e "s/^dn. uid=${username},ou=//" -e "s/,.*//" -e's/ *$//' -e 's/^ *//' | tr '[a-z]' '[A-Z]' | sed -e 's/ *$//' -e 's/^ *//'`
else
 cn="System"
 sn="System"
 gn="System"
 dn="System"
 ou="SYSTEM"
fi

name="$cn"
if [ x"$ou" == xSMART ] ; then name="$gn" ; fi
if [ x"$ou" == xCADIT ] ; then name="$gn" ; fi
echo $cn | grep '^Cn::' > /dev/null && name="$gn"
if [ x"$gn" != x. ] ; then echo $cn | grep ' ' > /dev/null || name="$gn" ; fi

case $username in
 fsg1) name="Srikanth Gumma" ;;
 fsg3) name="Nick Wilson" ;;
 fsg5) name="Hirwan Mohamad" ;;
 gokej) name="Jonathan Göke" ;;
 arie) name="Arié Benhamou" ;;
 eloi) name="Éloi Fontaine" ;;
 zhouli) name="Zhou Li" ;;
 prakkisr) name="Prakki Sai Rama Sridatta" ;;
 altairsup) name="Altair Suppport" ;;
 altairsup2) name="Altair Support" ;;
 tmsndte) name="Ethan Nguyen" ;;
 robsimps) name="$gn" ;;
esac

case $username in
 fsg1) ou="NSCC" ;;
 fsg2) ou="NSCC" ;;
 fsg3) ou="NSCC" ;;
 fsg4) ou="NSCC" ;;
 fsg5) ou="NSCC" ;;
 fjj1) ou="NSCC" ;;
 fjj2) ou="NSCC" ;;
 fjj3) ou="NSCC" ;;
 fjj4) ou="NSCC" ;;
 fjj5) ou="NSCC" ;;
 fjj6) ou="NSCC" ;;
 bmt1) ou="NSCC" ;;
 bmt2) ou="NSCC" ;;
 bmt3) ou="NSCC" ;;
 bmt4) ou="NSCC" ;;
 ngtc1) ou="NSCC" ;;
 ngtc2) ou="NSCC" ;;
 ngtc3) ou="NSCC" ;;
 altairsup) ou="NSCC" ;;
 altairsup2) ou="NSCC" ;;
 ddnsupport) ou="NSCC" ;;
 portaladmin) ou="NSCC" ;;
 hows) ou="IHPC" ;;
 ntu.melvin) ou="NTU" ;;
 hiewnh) ou="NSCC" ;;
 sheny) ou="NSCC" ;;
 waimeng) ou="NSCC" ;;
 testacct) ou="NSCC" ;;
 jeffreyho) ou="NSCC" ;;
 secpjf) ou="ETHZ" ;;
 nrdmgb) ou="NRD" ;;
 nrdzw) ou="NRD" ;;
 nrdmela) ou="NRD" ;;
 nrdnbka) ou="NRD" ;;
 sbbrlg) ou="SINBERBEST" ;;
 smrqx) ou="SMART" ;;
 smrpvr) ou="SMART" ;;
 tumjiaj) ou="TUM-CREATE" ;;
esac

case $ou in
 "DN: UID=PORTALADMIN") ou=ALTAIR ;;
 "IHPC TO_BE_CONFIRMED") ou=IHPC ;;
esac
if [ x"$ou" == xMIT ] ; then ou=SMART ; fi

# Set high-level orgs
ouh="Other"
ldapsearch -x -LLL "(uid=$username)" | grep ^dn: | grep ,ou=industry, > /dev/null && ouh="Industry"
echo $ou | grep NUS > /dev/null && ouh="NUS"
case $ou in
 NTU) ouh='NTU' ;;
 GIS) ouh='A*STAR' ;;
 IHPC) ouh='A*STAR' ;;
 BII) ouh='A*STAR' ;;
 IMCB) ouh='A*STAR' ;;
 SCEI) ouh='A*STAR' ;;
 I2R) ouh='A*STAR' ;;
 BMSI) ouh='A*STAR' ;;
 ICES) ouh='A*STAR' ;;
 DSI) ouh='A*STAR' ;;
 IMRE) ouh='A*STAR' ;;
 IME) ouh='A*STAR' ;;
 SIMT) ouh='A*STAR' ;;
 IBN) ouh='A*STAR' ;;
 CREATE) ouh='CREATE' ;;
 BEARS-BERKELEY) ouh='CREATE' ;;
 CARES) ouh='CREATE' ;;
 E2S2) ouh='CREATE' ;;
 ETHZ) ouh='CREATE' ;;
 NRD) ouh='CREATE' ;;
 SINBERBEST) ouh='CREATE' ;;
 SINBERISE) ouh='CREATE' ;;
 SMART) ouh='CREATE' ;;
 TUM-CREATE) ouh='CREATE' ;;
 SUTD) ouh='SUTD' ;;
 SMU) ouh='SMU' ;;
 SERI) ouh='Industry' ;;
esac
 echo ${username},${name},${ou},${ouh},${cn},${sn},${gn},${dn} >> "$usernames_raw_csv"
 echo ${username},${name},${ou},${ouh} >> "$usernames_csv"
done
