#!/bin/bash
cd `dirname "$0"` || exit $?

. ./config

if [ $publish -eq 1 ] ; then
 echo Copy files to stakeholder home directories and update myusage command data
 # requires root permission
 su -c ./make-copyout
fi

# High level institutes
orgs="ASTAR NUS NTU CREATE SUTD SMU Industry Other"
# Individual organizations
orgs="$orgs GIS IHPC KOMTECH"
orgs="$orgs MACHINELEARNING"
#orgs="$orgs BEARS-BERKELEY CARES E2S2 ETHZ NRD SINBERBEST SINBERISE SMART TUM-CREATE"

# base directory
base=/app/nsccadmin/log

# Copy data to log directory
logdir=$base/usage-statistics
outputfiles=`echo {active,alldata,top100,total,org,application,user_,stats_by_core,cpu_walltime_by_user_by_application_,storage,project_,ams-}*.$suffix.csv`

rm -f $logdir/partial/*.$suffix.csv  $logdir/partial/by-org/*.$suffix.csv
if [ x"$type" == xpartial ] ; then
 mkdir -p $logdir/partial/by-org && \
 cp -pv $outputfiles $logdir/partial/ && \
 for org in $orgs ; do
  mv -v $logdir/partial/*.$org.$suffix.csv $logdir/partial/by-org/
 done
elif [ x"$suffix" == xaggregate ] ; then
 mkdir -p $logdir/aggregate/by-org && \
 cp -pv $outputfiles $logdir/aggregate/ && \
 for org in $orgs ; do
  mv -v $logdir/aggregate/*.$org.$suffix.csv $logdir/aggregate/by-org/
 done
elif [ $monthly -eq 1 ] ; then
 mkdir -p $logdir/by-org && \
 cp -pv $outputfiles $logdir/ && \
 for org in $orgs ; do
  mv -v $logdir/*.$org.$suffix.csv $logdir/by-org/
 done
else
 mkdir -p $logdir/weekly && \
 cp -pv $outputfiles $logdir/weekly/
fi

# Set appropriate file permissions on data
./fix-permissions
