#!/bin/bash
. ./config

in="unused-mean.$suffix.csv"
out="unused.$suffix.csv"

if [ -f "$out" ] ; then exit ; fi

if [ ! -f "$in" ] ; then
 if [ -d system-utilisation ] ; then
  (cd system-utilisation && ./run)
 fi
fi

if [ ! -f "$out" ] ; then
cat << EOF > $out
"Organization","Organization.HighLevel","CoreHours","NumJobs"
"GIS-UNUSED","A*STAR","0.0","0"
EOF
