#!/bin/bash

. ./config

rawfile="pbs-report.raw.$suffix.csv"
csvfile="pbs-report.cleaned.$suffix.csv"

if [ ! -f "$rawfile" ] ; then
 echo Missing: $rawfile
 exit 1
fi

echo cleaning $rawfile into $csvfile
((n=0))
while read line ; do
if [ x"$line" = x ] ; then ((n=n+1)) ; continue ; fi
if [ $n -eq 2 ] ; then
 echo "$line" | sed -e 's,Suspend$,Suspend|,' | \
   awk -F\| '{if ( NF == 16 ) {OFS="|" ; a=$4"_"$5 ; print $1,$2,$3,a,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16;} else \
             {if ( NF == 17 ) {OFS="|" ; a=$4"_"$5"_"$6 ; print $1,$2,$3,a,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17;} else {print $0;};};}'
fi
done < "$rawfile" > "$csvfile"

check=`awk -F\| '{print NF}' "$csvfile" | uniq`
if [ x"$check" != x15 ] ;then
 echo ERROR: cleaning data shows malformed data: $check
 exit 1
fi
