#!/bin/sh

cd `dirname $0` || exit $?

. ./config
if [ ! -d archive/totals/${ey}${em}${ed} ] ; then
 if [ -f total.aggregate.csv ] ; then
  mkdir archive/totals/${ey}${em}${ed} && \
   cp -p total*.aggregate.csv archive/totals/${ey}${em}${ed}/
 fi
fi

(cd archive/totals && ./gather)
cp -p archive/totals/totals.csv /app/nsccadmin/log/usage-statistics/aggregate/aggregate-bymonth.csv
cp -p archive/totals/totals.csv /app/nsccadmin/log/usage-statistics/
