#!/bin/sh
f=totals.csv
echo cpu , gpu , combined ,  ,  , nus , astar , ntu , create  , other| tee $f
 nc=`tail -n 1 total.aggregate.csv | awk -F, '{print $3}'`
 ng=`tail -n 1 total.aggregate.csv | awk -F, '{print $4}'`
 nt=`tail -n 1 total.aggregate.csv | awk -F, '{print $2}'`
 n_nus=`tail -n 1 total.NUS.aggregate.csv | awk -F, '{print $2}'`
 n_astar=`tail -n 1 total.ASTAR.aggregate.csv | awk -F, '{print $2}'`
 n_ntu=`tail -n 1 total.NTU.aggregate.csv | awk -F, '{print $2}'`
 n_create=`tail -n 1 total.CREATE.aggregate.csv | awk -F, '{print $2}'`
 n_other=`echo $nt $n_nus $n_astar $n_ntu $n_create | awk '{printf "%.5f",$1-$2-$3-$4-$5}'`
 echo $nc , $ng , $nt ,  ,  , $n_nus , $n_astar , $n_ntu , $n_create , $n_other | tee -a $f
