#!/bin/bash
. ./config
./get-pbsreport $sy $sm $sd $ey $em $ed
./generate-application-statistics
#cp -p /app/nsccadmin/log/usage-statistics/*.NUS.* ~ccewjh/Monthly_Usage/ && chown ccewjh.nus ~ccewjh/Monthly_Usage/*
