#!/bin/bash

# This script has settings required to run statistics in cron as root on wlm01
# crontab setting:
# 00 08 29 * * d=/app/nsccadmin/apps/usage-statistics/reports/weekly/20170802-20170808 ; s=run-cron-root-wlm01 ; $d/$s > $d/$s.stdout 2>&1
#
# TODO: replace manual second pass with: run pbsreport, update qstat and job information, generate statistics


cd `dirname $0`

export PATH="/app/pbs/bin:$PATH:/opt/pbs/default/bin:/opt/pbs/default/sbin"

. /etc/profile.d/modules.sh
. /app/modules/modules.sh
module load R
which Rscript

if [ 0 -eq 1 ] ; then
x=`ps -ef | grep appstats-archive-cron | grep -v grep`
while [ x"$x" != x ] ; do
 sleep 60
 x=`ps -ef | grep appstats-archive-cron | grep -v grep`
done
fi

echo first make, only interested in pbs-report data
make

echo get latest application and project data
if [ -x ./tmp.get-qstat ] ; then ./tmp.get-qstat ; fi
echo redo alljobs
if [ -x ./tmp.redo-alljobs ] ; then su fsg3 -c ./tmp.redo-alljobs ; fi

echo second pass of statistics
. ./config
rm -f alljobs.$suffix.csv project.$suffix.csv
make

echo Update myusage data
./update-myusage

echo Copy out output files
chown -R fsg3.nscc-proj .
. ./config
base=/app/nsccadmin/log
logdir=$base/usage-statistics
outputfiles=`echo {active,alldata,top100,total,org,application,user_,stats_by_core,cpu_walltime_by_user_by_application_,storage,project_}*.$suffix.csv`
if [ x"$suffix" == xaggregate ] ; then
 cp -p $outputfiles $logdir/aggregate/
elif [ $monthly -eq 1 ] ; then
 cp -p $outputfiles $logdir/
else
 cp -p $outputfiles $logdir/weekly/
fi
