#!/bin/bash

umask 077

. ./config

if [ x"$type" == xaggregate ] ; then
 p=aggregate
elif [ x"$type" == xmonthly ] ; then
 p=month
elif [ x"$type" == xweekly ] ; then
 p=week
else
 echo updating myusage for this report type \(${type}\) is not required
 exit
fi

logdir=/app/nscc/log/user_usage
chown root.nscc-proj "$logdir"
chmod 0751 "$logdir"
for cpu in cpu gpu ; do
 if [ ! -d "$logdir/$cpu" ] ; then mkdir "$logdir/$cpu" ; fi
 chown root.nscc-proj "$logdir/$cpu"
 chmod 0751 "$logdir/$cpu"
 for pp in week month aggregate ; do
  if [ ! -d "$logdir/$cpu/$pp" ] ; then mkdir "$logdir/$cpu/$pp" ; fi
  chown root.nscc-proj "$logdir/$cpu/$pp"
  chmod 0751 "$logdir/$cpu/$pp"
 done
done

getent passwd | awk -F: '{print $1}' | while read u ; do 
echo extracting data for $u

for cpu in cpu gpu ; do

col=5
if [ x"$cpu" == xgpu ] ; then col=8 ; fi
f="$logdir/$cpu/$p/$u"
 rm -f "$f" || break
 grep \"$u\" user_walltime_$cpu.$suffix.csv | \
  awk -F, '{printf "'$ey/$em/$ed' %'\''d %'\''.1f\n",$6,$'$col'}' > "$f"
 if [ ! -s "$f" ] ; then echo $ey/$em/$ed 0 0.0 > "$f" ; fi
 chown $u "$f"
 chgrp nscc-proj "$f"
 chmod a-wx,ug+r,o-r "$f"
done

done

if [ x"$1" == x"--all" ] ; then
 shift
 echo update full user statistics
 ./update-myusage-all "$@"
fi

if [ x"$type" == xmonthly ] ; then
d=$logdir/project
f="project_by_user.$suffix.csv"
sed -e 's/"//g' $f | awk -F, '{print $9}' | egrep -v '^(Project_Short|Unknown|personal-|resv|Personal)' | sort | uniq | while read p ; do
 echo extracting project data for $p
 if [ ! -f "$d/$p" ] ; then echo Month,Project,CoreHours,Jobs > "$d/$p" ; fi
 awk -F, '{if ( $9 == "\"'$p'\"" ) {printf "\"'$suffix'\",%s,%s,%.1f,%d\n",$9,$2,$5,$6;};}' $f >> "$d/$p"
 chown root "$d/$p" 
 chgrp nscc-proj "$d/$p"
 chmod a-wx,ug+r,o-r "$d/$p"
 users=`awk -F, '{if ( $9 == "\"'$p'\"" ) {print $2}}' $f | sed -e 's/"//g' | sort | uniq`
 for u in $users ; do
  if [ ! -f "$d/$p.$u" ] ; then echo Month,Project,CoreHours,Jobs > "$d/$p.$u" ; fi
  awk -F, '{if ( $9 == "\"'$p'\"" && $2 == "\"'$u'\"" ) {printf "\"'$suffix'\",%s,%s,%.1f,%d\n",$9,$2,$5,$6;};}' $f >> "$d/$p.$u"
  chown $u "$d/$p.$u" 
  chgrp nscc-proj "$d/$p.$u"
  chmod a-wx,ug+r,o-r "$d/$p.$u"
 done
done
fi

if [ -x dgx/update-myusage ] ; then
 (cd dgx && ./update-myusage)
fi
